- hosts: localhost
  tasks:
  - name: run ontap cli command
#    netapp.ontap.na_ontap_command:
    na_ontap_command:
      hostname: "192.168.1.220" 
      username: "admin"
      password: "info0101"
      https: true
      validate_certs: false
      command: ['version']
    register: ontap_info


  - name: Prints 
    debug:
      msg:
      - "Provisioning based on YOUR_KEY which isxxx"
      - "{{ ontap_info }}"
