- hosts: localhost
  tasks:
  - name: Limit Info Gathering to vserver Information as Cluster Admin
    na_ontap_info:
      hostname: "192.168.1.220"
      username: "admin"
      password: "info0101"
      https: true
      validate_certs: false
      gather_subset: "vserver_info"
    register: ontap_info


  - name: Prints two lines of messages, but only if there is an environment value set
    debug:
      msg:
      - "Provisioning based on YOUR_KEY which isxxx"
      - "{{ ontap_info }}"
